name: Publish docker image
description: ""

inputs:
  token:
    description: ""
    required: true
  tags:
    description: ""
    required: true
  registry:
    description: ""
    required: true
  file:
    description: ""
    required: true
  context:
    description: ""
    default: .
  build-args:
    description: ""
    default: ""
  platforms:
    description: ""
    default: ""

runs:
  using: composite
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.repository_owner }}
        password: ${{ inputs.token }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: ${{ inputs.file }}
        context: ${{ inputs.context }}
        build-args: ${{ inputs.build-args }}
        platforms: ${{ inputs.platforms }}
        provenance: false
        push: true
        tags: ${{ inputs.tags }}
